TrajectoryPlannerROS:

# Robot Configuration Parameters - 提高速度
  max_vel_x: 0.8        # 提高X方向最大速度
  min_vel_x: 0.3        # 提高最小速度避免太慢
  
  max_vel_theta: 1.2    # 提高角速度
  min_vel_theta: -1.2
  min_in_place_vel_theta: 1.0  # 提高原地旋转速度

  acc_lim_x: 1       # 提高加速度响应
  acc_lim_y: 0.0
  acc_lim_theta: 1    # 提高角加速度

# Goal Tolerance Parameters
  xy_goal_tolerance: 0.15
  yaw_goal_tolerance: 0.1
  latch_xy_goal_tolerance: true

# Differential-drive robot configuration
  holonomic_robot: false

# Forward Simulation Parameters - 优化响应性
  sim_time: 1.0         # 减少仿真时间提高响应
  vx_samples: 10        # 减少采样提高效率
  vtheta_samples: 12
  sim_granularity: 0.03

# Trajectory scoring parameters
  path_distance_bias: 64.0
  goal_distance_bias: 24.0
  occdist_scale: 0.5
  max_scaling_factor: 0.2
