# cleaning_costmap_params.yaml
# 
# 配置清扫机器人导航的代价地图参数。
#
# cleaning_costmap:
#   global_frame: 地图的全局坐标系名称。
#   robot_base_frame: 机器人底盘坐标系名称。
#   update_frequency: 代价地图更新频率（Hz）。
#   publish_frequency: 代价地图发布频率（Hz）。
#   static_map: 是否使用静态地图（true为使用）。
#   rolling_window: 是否使用滚动窗口（false为全局地图）。
#   resolution: 地图分辨率（米/像素）。
#   transform_tolerance: 坐标变换的容忍时间（秒）。
#   inflation_radius: 膨胀半径（米），用于障碍物膨胀。
#   map_type: 代价地图类型（如costmap）。
#
# cleaning_plan_nodehandle:
#   size_of_cell: 单元格的大小（单位自定义，通常为像素或网格数）。
#   grid_covered_value: 标记已覆盖区域的值。
cleaning_costmap:
   global_frame: map
   robot_base_frame: base_footprint
   update_frequency: 1.0
   publish_frequency: 1.0
   static_map: true
   rolling_window: false
   resolution: 0.09
   transform_tolerance: 1.0
   inflation_radius: 0.15
   map_type: costmap

cleaning_plan_nodehandle:   
   size_of_cell: 3
   grid_covered_value: 200